### ISSUE TITLE
TextGraphs2018-discovery No train_dev.csv

### ISSUE THREAD

**Issue by Tavisius25** [clulab/releases#1]
I'm interested in running the classifiers.py code and the x and y training data is constructed from the train_dev.csv file. This file doesn't seem to exist in the processed_data folder. Furthermore, many of the negative training csv files seem to be missing for the training split. Is this by design? In its current state it does not seem like others can train these models.

**Comment by MihaiSurdeanu** [comment]
@Fan-Luom @myedibleenso: can you please share the dataset?

**Comment by MihaiSurdeanu** [comment]
typo: I meant @Fan-Luo

**Comment by Fan-Luo** [comment]
Missing data files have been uploaded. The files are larger than GitHub's recommended maximum file size of 50.00 MB, we were thinking to move these files to other place, and probability do so sooner or later.

**Comment by kwalcock** [comment]
FWIW GitHub has a way to deal with large files, but it involves some extra software.  We might be needing it for Eidos resources.

**Comment by Tavisius25** [comment]
Thank you for the fast response.
