### ISSUE TITLE
is_projective loop in lrec2020-pat

### ISSUE THREAD

**Issue by Sharefah-Alghamdi** [clulab/releases#4]
I am trying to run the code for lrec2020-pat on my dataset
but it seems that it go into infinet loop in function
is_projective(sentence)
in colln.py
here->
unassigned = {
        entry.id: sum(1 for e in sentence if e.head == entry.id)
        for entry in sentence
    }

What do you think the reason is?

**Comment by robertvacareanu** [comment]
Can you share the sentence that triggers this behavior?

**Comment by Sharefah-Alghamdi** [comment]
Thank you for your reply!
I found the reason 👍 
It was that I don't add an empty line between sentences!

**Comment by robertvacareanu** [comment]
Glad it was solved :+1:
